//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForeignExchangeMX.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ForeignExchangeMX.Resources.Resource", typeof(Resource).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        public static string AmountValidation {
            get {
                return ResourceManager.GetString("AmountValidation", resourceCulture);
            }
        }
        
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        public static string AmountNumericValidation {
            get {
                return ResourceManager.GetString("AmountNumericValidation", resourceCulture);
            }
        }
        
        public static string SourceRateValidation {
            get {
                return ResourceManager.GetString("SourceRateValidation", resourceCulture);
            }
        }
        
        public static string TargetRateValidation {
            get {
                return ResourceManager.GetString("TargetRateValidation", resourceCulture);
            }
        }
        
        public static string AmountLabel {
            get {
                return ResourceManager.GetString("AmountLabel", resourceCulture);
            }
        }
        
        public static string AmountPlaceHolder {
            get {
                return ResourceManager.GetString("AmountPlaceHolder", resourceCulture);
            }
        }
        
        public static string SourceRateLabel {
            get {
                return ResourceManager.GetString("SourceRateLabel", resourceCulture);
            }
        }
        
        public static string SourceRateTitle {
            get {
                return ResourceManager.GetString("SourceRateTitle", resourceCulture);
            }
        }
        
        public static string TargetRateLabel {
            get {
                return ResourceManager.GetString("TargetRateLabel", resourceCulture);
            }
        }
        
        public static string TargetRateTitle {
            get {
                return ResourceManager.GetString("TargetRateTitle", resourceCulture);
            }
        }
        
        public static string Convert {
            get {
                return ResourceManager.GetString("Convert", resourceCulture);
            }
        }
        
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        public static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        public static string SettingInternetError {
            get {
                return ResourceManager.GetString("SettingInternetError", resourceCulture);
            }
        }
        
        public static string ConnectionInternetError {
            get {
                return ResourceManager.GetString("ConnectionInternetError", resourceCulture);
            }
        }
        
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
    }
}
